version: '3.3'
services:
  person:
    image: person:latest
    container_name: person
    environment:
      RABBITMQ_HOST: amqp://root:root@rabbitmq:5672/
      MYSQL_HOST: database
      CONSUL_URL: consul:8500
    ports:
      - 8000:8000

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'      
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped

  consul:
    image: consul:1.15.4
    ports:
      - 8500:8500
    command: [ "agent", "-dev", "-client", "0.0.0.0" ]

volumes:
  rabbitmq_data:
  rabbitmq_logs: